version: '2'
services:
  web:
    image: neelbhat88/imua
    env_file:
      - '.env'
    volumes:
      - '.:/imua'
    ports:
      - "3000:3000"
    volumes_from:
      - bundle
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"

  bundle:
    image: busybox
    volumes:
      - /bundle
